vich_uploader:
    db_driver: orm

    mappings:
        article_image:
            uri_prefix: assets/images
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
