# config/services.yaml

parameters:

services:
    # App\Form\DevisType:
    #     tags: ['form.type']
        
    # Configuration par défaut pour les services de ce fichier
    _defaults:
        autowire: true       # Injecte automatiquement les dépendances dans vos services.
        autoconfigure: true  # Enregistre automatiquement vos services en tant que commandes, abonnements d'événements, etc.

    # Permet d'utiliser les classes du répertoire src/ comme services.
    # Cela crée un service par classe, dont l'identifiant est le nom de classe entièrement qualifié.
    App\:
        resource: '../src/'
        exclude:
            - '../src/Controller/DevisController.php'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Définition du service PDFGenerator
    App\PDFGenerator:
        class: App\PDFGenerator

    # Configuration du contrôleur DevisController en tant que service
    App\Controller\DevisController:
        public: true
        tags: ['controller.service_arguments']
